# Generated by Django 4.0.4 on 2022-06-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntregable', '0002_bibliotecas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
